INSERT INTO Studio (studio_name, rating) VALUES
('10Gauge', 2),
('3D', 2),
('81 Produce', 2),
('8bit', 5),
('A-1 Pictures', 5),
('A-Line', 2),
('A.C.G.T.', 5),
('AC Create', 2),
('ACC Production', 4),
('ACiD FiLM', 2),
('AIC', 5),
('AIC ASTA', 5),
('AIC Build', 4),
('AIC Classic', 4),
('AIC Frontier', 3),
('AIC PLUS+', 5),
('AIC Spirits', 5),
('AIC Takarazuka', 2),
('APPP', 5),
('AYCO', 2),
('Academy Productions', 3),
('Actas', 5),
('Agent 21', 3),
('Ajia-do', 5),
('Amber Film Works', 3),
('An DerCen', 2),
('Anima', 3),
('Animaruya', 4),
('Animation 21', 4),
('Animation 501', 2),
('Animation Do', 3),
('Animation Planet', 2),
('Animation Staff Room', 3),
('Animation Studio Wagumi', 2),
('Anime R', 3),
('Annapuru', 2),
('Anpro', 4),
('Arcs Create', 2),
('Arcturus', 2),
('Arms', 5),
('Artland', 5),
('Artmic', 5),
('Asahi Production', 5),
('Ascension', 3),
('Ashi Productions', 5),
('Assez Finaud Fabric', 2),
('Aubeck', 5),
('Automatic Flowers Studio', 2),
('Axis', 2),
('Azeta Pictures', 3),
('B&T', 2),
('Bandai Namco Pictures', 2),
('Barnum Studio', 3),
('BeSTACK', 3),
('Beat Frog', 2),
('Bebow', 3),
('Bee Media', 4),
('Bee Train', 5),
('Beijing Huihuang Animation Company', 2),
('Big Bang', 3),
('Bones', 5),
('Brain''s Base', 5),
('Bridge', 4),
('Buyuu', 2),
('C-Station', 2),
('C2C', 4),
('Chaos Project', 5),
('Charaction', 3),
('Children''s Corner', 2),
('CinePix', 2),
('Circus Production', 2),
('CoMix Wave Films', 5),
('Code', 2),
('Comma Studio', 2),
('Connect', 3),
('Creators Dot Com', 2),
('Creators in Pack', 2),
('CyberConnect2', 2),
('Cyclone Graphics', 2),
('D.A.S.T Corporation', 3),
('DAX Production', 5),
('DLE', 5),
('DOGA Productions', 2),
('DR Movie', 2),
('Daewon Media', 4),
('Dai-Ichi Douga', 2),
('DandeLion Animation Studio', 2),
('Dangun Pictures', 2),
('Darts', 2),
('Daume', 5),
('David Production', 5),
('Deck', 2),
('Digital Dream Studios', 2),
('Digital Frontier', 4),
('Digital Media Lab', 3),
('Diomedéa', 5),
('Doga Kobo', 5),
('Dongwoo A&E', 5),
('Dyna Method', 2),
('Dynamic Planning', 2),
('Dynamo Pictures', 2),
('E&G Films', 5),
('Echoes', 2),
('Egg', 3),
('Eiken', 5),
('ElectromagneticWave', 2),
('Encourage Films', 3),
('Fanworks', 4),
('Felix Film', 2),
('Fifth Avenue', 2),
('Filmlink International', 3),
('Four Some', 2),
('Front Line', 3),
('Frontier Works', 2),
('Fuji TV', 2),
('Future Planet', 2),
('G&G Direction', 3),
('G&G Entertainment', 3),
('GANSIS', 3),
('GARDEN LODGE', 3),
('Gainax', 5),
('Gakken', 3),
('Gakken Eigakyoku', 2),
('Gallop', 5),
('Garyuu Studio', 2),
('Gathering', 5),
('Geno Studio', 2),
('Ginga Teikoku', 2),
('Ginga Ya', 3),
('GoHands', 5),
('Gonzino', 2),
('Gonzo', 5),
('Graphinica', 4),
('Group TAC', 5),
('Grouper Productions', 5),
('HAL Film Maker', 5),
('HOTZIPANG', 2),
('HS Pictures Studio', 2),
('Heewon Entertainment', 2),
('Hero', 2),
('Hiro Media', 3),
('Hong Ying Animation', 2),
('Hoods Entertainment', 5),
('Horannabi', 2),
('Hoso Seisaku Doga', 2),
('Hotline', 3),
('Husio Studio', 2),
('I was a Ballerina', 3),
('I-move', 2),
('I.Gzwei', 2),
('I.Toon', 2),
('ILCA', 2),
('Iconix Entertainment', 2),
('Idea Factory', 3),
('Idol', 2),
('Image Kei', 3),
('Imagi', 2),
('Imagica', 2),
('Imagin', 4),
('Indeprox', 2),
('Ishikawa Pro', 2),
('Ishimori Entertainment', 2),
('Itasca Studio', 2),
('Iyasakadou Film', 2),
('J.C.F.', 2),
('J.C.Staff', 5),
('JCF', 3),
('JM Animation', 2),
('Japan Vistec', 2),
('Jinnis Animation Studios', 3),
('Jumonji', 2),
('K-Factory', 3),
('KAGAYA Studio', 2),
('KOO-KI', 2),
('KSS', 4),
('Kachidoki Studio', 5),
('Kaeruotoko Shokai', 2),
('Kamikaze Douga', 2),
('Kanaban Graphics', 4),
('Kaname Productions', 4),
('Karaku', 2),
('Kate Arrow', 2),
('Kazami Gakuen Koushiki Douga-bu', 2),
('Kenji Studio', 2),
('Kent House', 2),
('KeyEast', 2),
('Khara', 4),
('Kinema Citrus', 5),
('Kino Production', 2),
('Kitty Film Mitaka Studio', 5),
('Knack Productions', 5),
('Kojiro Shishido Animation Works', 3),
('Kokusai Eigasha', 3),
('Kuri Jikken Manga Koubou', 5),
('Kyoto Animation', 5),
('LIDENFILMS', 5),
('LMD', 3),
('LandQ studios', 2),
('Larx Entertainment', 2),
('Lay-duce', 2),
('Lerche', 5),
('Liberty Animation Studio', 2),
('Life Work', 3),
('Lyrics', 3),
('M.S.C', 5),
('MAPPA', 5),
('MI', 2),
('MK Pictures', 2),
('MMDGP', 2),
('Mad Box', 2),
('Madhouse', 5),
('Magic Bus', 5),
('Maikaze', 2),
('Manglobe', 5),
('Marine Entertainment', 2),
('Marone', 2),
('Marvelous Entertainment', 2),
('Marvy Jack', 3),
('Marza Animation Planet', 2),
('Maxilla', 2),
('Meruhensha', 2),
('Milky Cartoon', 4),
('Millepensee', 2),
('Minakata Laboratory', 2),
('Minami Machi Bugyousho', 3),
('Mippei Eigeki Kiryuukan', 2),
('Mirai Film', 4),
('MontBlanc Pictures', 2),
('MooGoo', 3),
('Mook Animation', 3),
('Mook DLE', 2),
('Movic', 2),
('Mushi Production', 5),
('N&G Production', 2),
('NAZ', 3),
('NHK', 2),
('NHK Enterprises', 2),
('Nakamura Production', 2),
('Network Kouenji Studio', 2),
('Next Media Animation', 2),
('Nexus', 2),
('Nihon Hoso Eigasha', 3),
('Nippon Animation', 5),
('Nippon Ramayana Film', 2),
('Nippon TV Douga', 3),
('No Side', 3),
('Nomad', 5),
('OB Planning', 2),
('OLM', 5),
('OLM Digital', 3),
('ONIRO', 2),
('Ocon Studio', 2),
('Odolttogi', 2),
('Office AO', 3),
('Office Academy', 3),
('Office DCI', 2),
('Office No. 8', 2),
('Oh! Production', 4),
('Opera House', 2),
('Orange', 3),
('Ordet', 5),
('Oxybot', 3),
('P.A. Works', 5),
('PP Project', 3),
('PPM', 3),
('Palm Studio', 4),
('Panda Factory', 3),
('Panmedia', 2),
('Passione', 3),
('Pastel', 5),
('Phoenix Entertainment', 4),
('Picograph', 2),
('Picture Magic', 5),
('Pie in the sky', 2),
('Pierrot Plus', 5),
('Planet', 3),
('Plum', 4),
('Plus Heads', 2),
('Pollyanna Graphics', 2),
('Polygon Pictures', 5),
('Poncotan', 2),
('Primastea', 2),
('PrimeTime', 4),
('Production I.G', 5),
('Production IMS', 4),
('Production Reed', 5),
('Production Wave', 2),
('Project No.9', 4),
('Project Team Argos', 4),
('Project Team Eikyuu Kikan', 2),
('Project Team Sarah', 3),
('Public & Basic', 3),
('Purple Cow Studio Japan', 3),
('Puzzle Animation Studio Limited', 2),
('RAMS', 2),
('REALTHING', 2),
('RG Animation Studios', 5),
('Radix', 5),
('Remic', 3),
('Rikuentai', 4),
('Ripple Film', 2),
('Rising Force', 2),
('Robot Communications', 4),
('Romanov Films', 2),
('SANZIGEN', 5),
('SBS TV Production', 2),
('SIDO LIMITED', 3),
('SILVER LINK.', 5),
('San-X', 2),
('Sanctuary', 2),
('Sanrio', 3),
('Satelight', 5),
('Seoul Movie', 2),
('Seven', 5),
('Seven Arcs', 5),
('Seven Arcs Pictures', 3),
('Seven Stone Entertainment', 2),
('Shaft', 5),
('Shanghai Animation Film Studio', 4),
('Shelty', 2),
('Shimogumi', 2),
('Shin-Ei Animation', 5),
('Shinkuukan', 2),
('Shirogumi', 5),
('Shochiku Animation Institute', 4),
('Shogakukan Music & Digital Entertainment', 5),
('Shueisha', 2),
('Shuka', 2),
('Silver', 2),
('Soeishinsha', 2),
('Sofix', 2),
('Sola Digital Arts', 2),
('Sovat Theater', 2),
('Soyuzmultfilm', 2),
('Sparkly Key Animation Studio', 3),
('Sparky Animation', 2),
('Spooky graphic', 2),
('Square Enix Visual Works', 3),
('Square Pictures', 2),
('StarLink', 2),
('Steve N'' Steven', 2),
('Stingray', 2),
('Studio 3Hz', 2),
('Studio 4°C', 5),
('Studio 88', 3),
('Studio A-CAT', 2),
('Studio Animal', 2),
('Studio Barcelona', 4),
('Studio Bingo', 2),
('Studio Blanc.', 3),
('Studio Bogey', 3),
('Studio Chizu', 2),
('Studio Coa', 2),
('Studio Cockpit', 2),
('Studio Colorido', 3),
('Studio Comet', 5),
('Studio Core', 2),
('Studio Crocodile', 2),
('Studio Curtain', 2),
('Studio D-Volt', 2),
('Studio Dadashow', 2),
('Studio Deen', 5),
('Studio Egg', 3),
('Studio Fantasia', 5),
('Studio Flag', 3),
('Studio G7', 2),
('Studio Gazelle', 3),
('Studio Ghibli', 5),
('Studio Gokumi', 5),
('Studio Gram', 2),
('Studio Guts', 2),
('Studio Hakk', 2),
('Studio Hibari', 5),
('Studio Izena', 2),
('Studio Junio', 5),
('Studio KAI', 2),
('Studio Kajino', 3),
('Studio Kelmadick', 2),
('Studio Kikan', 4),
('Studio Korumi', 2),
('Studio Kyuuma', 3),
('Studio Live', 5),
('Studio March', 2),
('Studio Matrix', 3),
('Studio Meditation With a Pencil', 2),
('Studio Moriken', 3),
('Studio OX', 3),
('Studio Pastoral', 3),
('Studio Pierrot', 5),
('Studio Placebo', 2),
('Studio PuYUKAI', 3),
('Studio Ranmaru', 3),
('Studio Rikka', 4),
('Studio Sign', 4),
('Studio Signal', 4),
('Studio Take Off', 2),
('Studio Tron', 2),
('Studio Unicorn', 3),
('Studio World', 2),
('Studio Z5', 2),
('Studio Zero', 3),
('StudioRF Inc.', 2),
('Suna Kouhou', 2),
('Sunny Gapen', 2),
('Sunrise', 5),
('Sunshine Corporation', 2),
('Sunwoo Entertainment', 2),
('Synergy Japan', 3),
('SynergySP', 5),
('T.P.O', 2),
('TCJ', 5),
('TMS Entertainment', 5),
('TNK', 5),
('TROYCA', 2),
('TV Douga', 3),
('TYO Animations', 5),
('Takahashi Studio', 4),
('Takun Manga Box', 2),
('Tama Production', 2),
('Tatsunoko Production', 5),
('Tecarat', 2),
('Telecom Animation Film', 5),
('Teleimage', 2),
('Telescreen', 4),
('Tezuka Productions', 5),
('The Answer Studio', 5),
('Three-d', 2),
('Toei Animation', 5),
('Toei Video', 2),
('Tokyo Kids', 5),
('Tokyo Media Connections', 2),
('Tokyo Movie', 4),
('Tokyo Movie Shinsha', 5),
('Tokyo TV Douga', 3),
('Tomason', 2),
('Tomoyasu Murata Company', 3),
('Tonko House', 2),
('Topcraft', 4),
('Trans Arts', 5),
('Transistor Studio', 2),
('Tri-Slash', 2),
('Triangle Staff', 5),
('Trigger', 5),
('Trinet Entertainment', 5),
('Triple A', 2),
('Tsubasa Production', 2),
('Tsuburaya Productions', 2),
('Tsuchida Productions', 5),
('Twilight Town', 2),
('Ultra Super Pictures', 2),
('Urban Product', 3),
('VAP', 2),
('Vega Entertainment', 5),
('Venet', 4),
('Viewworks', 3),
('Visual 80', 5),
('W+K Tokyo', 2),
('WAO World', 5),
('Wako Production', 4),
('Watanabe Promotion', 2),
('Welz Animation Studios', 2),
('White Fox', 5),
('Wit Studio', 5),
('Woodpecker', 2),
('XEBEC M2', 3),
('Xebec', 5),
('Yamamura Animation', 5),
('Yamato Works', 2),
('Yaoyorozu', 3),
('Yuhodo', 2),
('Yumeta Company', 5),
('Zero-G Room', 4),
('Zexcs', 5),
('Zuiyo', 2),
('animate Film', 5),
('asread.', 5),
('drop', 2),
('dwarf', 4),
('feel.', 5),
('indigo line', 2),
('lxtl', 2),
('teamKG', 3),
('ufotable', 5),
('uzupiyo Animation & Digital Works', 2);
