INSERT INTO Studio (studio_name, rating) VALUES
('100studio', 4),
('10Gauge', 4),
('1IN', 2),
('2:10 Animation', 5),
('33 Collective', 2),
('3D', 2),
('5 Inc.', 2),
('6pucks', 2),
('717 Animation Studio', 3),
('7doc', 4),
('81 Produce', 2),
('8bit', 5),
('924 Studio', 2),
('A-1 Pictures', 5),
('A-Line', 3),
('A-Real', 4),
('A.C.G.T.', 5),
('A4A Inc.', 3),
('ABC Animation Studio', 2),
('ABJ COMPANY', 3),
('AC Create', 2),
('ACC Production', 4),
('ACiD FiLM', 3),
('AHA Entertainment', 3),
('AIC', 5),
('AIC ASTA', 5),
('AIC Build', 4),
('AIC Classic', 4),
('AIC Frontier', 3),
('AIC PLUS+', 5),
('AIC Project', 2),
('AIC Spirits', 5),
('AIC Takarazuka', 2),
('AION Studio', 2),
('ANIDO FILM', 2),
('ANYZAC', 3),
('AOI Pro.', 2),
('APPP', 5),
('AQUA ARIS', 5),
('ARCUS', 4),
('ARECT', 3),
('ASK Animation Studio', 4),
('ASTROBROS.', 2),
('AXsiZ', 5),
('AYCO', 2),
('Academy Productions', 4),
('Acca effe', 4),
('Actas', 5),
('Adonero', 2),
('Aeonium', 2),
('Agent 21', 3),
('Ai Si Animation Studio', 3),
('Ajia-do', 5),
('Akatsuki', 4),
('Albacrow', 2),
('Alfred Imageworks', 2),
('Alke', 2),
('Alpha Animation', 5),
('Alpha Group', 3),
('Amber Film Works', 3),
('Amineworks', 2),
('An DerCen', 2),
('Andraft', 4),
('Angle', 3),
('Anima', 5),
('Anima&Co.', 3),
('Animaruya', 4),
('Animation 21', 4),
('Animation 501', 2),
('Animation Do', 5),
('Animation Lab Japan', 2),
('Animation Planet', 2),
('Animation Staff Room', 4),
('Animation Studio Wagumi', 3),
('Anime Beans', 2),
('Anime R', 3),
('Anime Tokyo', 2),
('Ankama Animations', 2),
('Annapuru', 2),
('Anon Pictures', 4),
('Anpro', 4),
('Arch', 2),
('Arcs Create', 2),
('Arcturus', 2),
('Arms', 5),
('Artland', 5),
('Artmic', 5),
('Artner', 2),
('Arvo Animation', 5),
('Asahi Production', 5),
('Ascension', 5),
('Ashi Productions', 5),
('Asmik Ace', 2),
('Assez Finaud Fabric', 4),
('Atelier Pontdarc', 3),
('Atelier Tuki', 2),
('Atoonz', 4),
('Au Praxinoscope', 3),
('Aubeck', 5),
('Aurochs', 2),
('Aurora Animation', 2),
('Aurum Production', 2),
('Automatic Flowers Studio', 2),
('Avaco Creative Studios', 2),
('Axis', 2),
('Azeta Pictures', 3),
('B&T', 3),
('B.CMAY PICTURES', 5),
('BENTEN Film', 2),
('BUDDHA INC.', 2),
('BUG FILMS', 3),
('BUILD DREAM', 5),
('BYMENT', 5),
('Bakken Record', 4),
('Bandai Namco Filmworks', 2),
('Bandai Namco Pictures', 5),
('Barnum Studio', 4),
('BeSTACK', 3),
('Beat Frog', 2),
('Bebow', 2),
('Bee Media', 4),
('Bee Train', 5),
('Beijing Enlight Pictures', 2),
('Beijing Huihuang Animation Company', 2),
('Bellnox Films', 2),
('Benlai Pictures', 2),
('Bibury Animation CG', 2),
('Bibury Animation Studios', 5),
('Big Bang', 3),
('Big Firebird Culture', 5),
('Big Pine Animation Studio', 2),
('Bigcat Studio', 2),
('Blade', 5),
('Blaze Studio', 2),
('BloomZ', 2),
('Blue bread', 2),
('BlueArc Animation Studios', 2),
('Bones', 5),
('Bones Film', 4),
('Borutong', 2),
('Bouncy', 3),
('Boyan Pictures', 2),
('Brain''s Base', 5),
('Brians Film', 2),
('Brick Studio', 3),
('Bridge', 5),
('Brio Animation', 2),
('Bu Keneng de Shijie', 3),
('Buemon', 3),
('Buyuu', 2),
('C-Station', 5),
('C2C', 5),
('CALF', 5),
('CANON RECORDINGS', 3),
('CANOPUS', 2),
('CCTV Animation Group', 4),
('CEKAI', 2),
('CELAVIE', 2),
('CG Year', 5),
('CGCG Studio', 3),
('CHOCOLATE', 3),
('CLAP', 4),
('CMAY Animation', 2),
('CMC Media', 4),
('CUCURI', 2),
('CUEBiC', 3),
('Caviar', 3),
('Central Animation Studio', 2),
('Chaos Project', 5),
('Charaction', 4),
('Chenghuang Yinghua', 2),
('Children''s Corner', 2),
('Children''s Playground Entertainment', 4),
('Chiptune', 2),
('Chongzhuo Animation', 2),
('Chosen', 4),
('CinePix', 2),
('Circus Production', 2),
('Climax Studio', 2),
('Cloud Art', 5),
('Cloud Culture', 2),
('Cloud Hearts', 4),
('CloverWorks', 5),
('CoMix Wave Films', 5),
('Coastline Animation Studio', 2),
('Cocktail Media', 2),
('Code', 2),
('Colored Pencil Animation', 5),
('Colored Pencil Animation Japan', 3),
('Comma Studio', 5),
('CompTown', 3),
('Composition Inc.', 3),
('Congrong Film', 3),
('Connect', 5),
('Contrail', 3),
('Craftar Studios', 5),
('Creative House Pocket', 2),
('Creative Power Entertaining', 2),
('Creators Dot Com', 3),
('Creators in Pack', 5),
('Creatures', 4),
('Crew-Cell', 2),
('Cue', 2),
('CyberConnect2', 3),
('Cyclone Graphics', 3),
('CygamesPictures', 5),
('D & D Pictures', 5),
('D''ART Shtajio', 2),
('D.A.S.T Corporation', 3),
('D.ROCK-ART', 3),
('DAX Production', 5),
('DC Impression Vision', 4),
('DEFT', 2),
('DLE', 5),
('DMM.futureworks', 5),
('DOGA Productions', 2),
('DR Movie', 4),
('DRAWIZ', 3),
('Da Chenger Gongzuoshi', 2),
('Daewon Media', 5),
('Dai-Ichi Douga', 2),
('Dancing CG Studio', 3),
('DandeLion Animation Studio', 5),
('Dangun Pictures', 3),
('Darts', 2),
('Daume', 5),
('David Production', 5),
('Dawn Animation', 2),
('Dazzling Star', 3),
('Deck', 2),
('Decovocal', 4),
('Delight Animation', 2),
('Delpic', 2),
('Digital Dream Studios', 3),
('Digital Frontier', 4),
('Digital Media Lab', 3),
('Digital Network Animation', 3),
('Diomedéa', 5),
('Directions', 2),
('Djinn Power', 2),
('Doga Kobo', 5),
('Dongwoo A&E', 5),
('Drawing and Manual', 2),
('Drive', 5),
('Durandal', 2),
('Durufix', 4),
('Dyna Method', 2),
('Dynamic Planning', 2),
('Dynamo Pictures', 4),
('E&G Films', 5),
('E&H Production', 4),
('EDP graphic works', 2),
('EKACHI EPILKA', 3),
('EMT Squared', 5),
('ENGI', 5),
('EOTA', 2),
('Eallin', 4),
('Earth Design Works', 2),
('East Fish Studio', 5),
('Echoes', 5),
('Egg', 3),
('Egg Firm', 3),
('Eiken', 5),
('Ekakiya', 2),
('Ekura Animal', 3),
('ElectromagneticWave', 2),
('Elias', 3),
('Emon', 2),
('Encourage Films', 5),
('Enishiya', 4),
('Enjin Productions', 3),
('Escape Velocity Animation', 3),
('Euluca Lab', 2),
('Ezόla', 3),
('FAB', 2),
('FILMONY', 3),
('FIREBUG', 2),
('FOREST Hunting One', 3),
('FUNNY MOVIE', 3),
('Fantawild Animation', 5),
('Fanworks', 5),
('Felix Film', 5),
('Fengyun Animation', 2),
('Fenz', 5),
('Fever Creations', 3),
('Fifth Avenue', 2),
('Filmlink International', 3),
('Finger and Toe', 2),
('Flagship Line', 2),
('Flat Studio', 5),
('Flint Sugar', 2),
('Flying Fish Studio', 3),
('Flying Monkeys Production', 2),
('Flying Ship Studio', 2),
('Foch Film', 5),
('Folium', 3),
('Fortes', 2),
('Four Some', 3),
('Friendly Land', 2),
('Front Line', 3),
('Front Wing', 2),
('Frontier One', 2),
('Frontier Works', 2),
('Fugaku', 3),
('Fuji TV', 2),
('Fukushima Gaina', 3),
('Funny Flux', 5),
('Future Planet', 2),
('G&G Direction', 3),
('G&G Entertainment', 3),
('G-angle', 5),
('G.H.Y. Culture & Media', 2),
('GANSIS', 3),
('GARDEN Culture', 5),
('GARDEN LODGE', 4),
('GEMBA', 4),
('GRIZZLY', 3),
('GUMBLAB', 2),
('Ga-Crew', 3),
('Gaina', 5),
('Gainax', 5),
('Gainax Kyoto', 3),
('Gakken', 3),
('Gakken Eigakyoku', 4),
('Gallop', 5),
('Gambit', 2),
('Garage Film', 4),
('Garyuu Studio', 2),
('Gathering', 5),
('Gear Studio', 2),
('Geek Toys', 5),
('Gekkou', 5),
('Genco', 2),
('Geno Studio', 5),
('Gift-o’-Animation', 5),
('Giga Production', 3),
('Ginga Teikoku', 2),
('Ginga Ya', 3),
('GoHands', 5),
('Gonzino', 2),
('Gonzo', 5),
('Gosay Studio', 2),
('Goto Inc.', 2),
('Graphinica', 5),
('Gravity Well', 4),
('Grayscale Arts', 2),
('Green Monster Team', 2),
('Griot Groove', 2),
('Grom', 2),
('Group Creato', 2),
('Group TAC', 5),
('Grouper Productions', 5),
('Guangzhou Liu Ling Yi', 2),
('Guo Pengzi Studio', 3),
('Guton Animation Studio', 3),
('Gyorai Eizo Inc.', 4),
('HAL Film Maker', 5),
('HIDEHOMARE', 2),
('HM Heros', 3),
('HMCH', 5),
('HORNETS', 4),
('HOTZIPANG', 5),
('HS Pictures Studio', 3),
('Haianxian Donghua Gongzuoshi', 2),
('Hananona Studio', 2),
('Hand to Mouse.', 3),
('Haneda xR Studio', 3),
('Hanho Heung-Up', 3),
('Haoliners Animation League', 5),
('Happy Elements', 5),
('Happy Toon', 2),
('Hayabusa Film', 3),
('HeART-BIT', 2),
('Heart & Soul Animation', 3),
('Heewon Entertainment', 2),
('Hei Chao Yinghua', 2),
('Hero', 2),
('Hezmon Animation', 2),
('Hifumi', 4),
('Higashinaka Studio', 2),
('High Energy Studio', 2),
('Hiro Media', 3),
('Hololive Production', 5),
('Hong Ying Animation', 2),
('Honoo', 2),
('Hoods Entertainment', 5),
('Horannabi', 2),
('HoriPro', 2),
('Hoso Seisaku Doga', 2),
('Hotline', 4),
('Hu Po Donghua', 2),
('HuaDream', 2),
('HuaMei Animation', 3),
('Hurray!', 5),
('Husio Studio', 3),
('Hutoon Animation', 5),
('I was a Ballerina', 5),
('I&A', 2),
('I-move', 3),
('I.Gzwei', 4),
('I.Toon', 3),
('IKIF+', 2),
('ILCA', 5),
('ILCASHIPS', 3),
('IMAGICA Lab.', 4),
('INS Studio', 4),
('INTERFACEDOGS', 2),
('Ice Butter', 2),
('Iconix Entertainment', 5),
('Idea Factory', 3),
('Idol', 2),
('Igloo Studio', 2),
('Ijigen Tokyo', 5),
('Image Kei', 3),
('Image Studio 109', 2),
('Imagestone Inc.', 2),
('Imageworks Studio', 5),
('Imagi', 2),
('Imagica', 2),
('Imagica Digitalscape', 2),
('Imagica Imageworks', 2),
('Imagica Infos', 5),
('Imagin', 4),
('Imagineer', 3),
('Indeprox', 2),
('Indivision', 2),
('InfiniOrange Animation Studio', 2),
('Infinity Animations', 2),
('Infinity Vision', 3),
('Ishikawa Pro', 4),
('Ishimori Entertainment', 2),
('Issen', 3),
('Itasca Studio', 2),
('Iyasakadou Film', 2),
('J.C.F.', 2),
('J.C.Staff', 5),
('JCF', 3),
('JJJOY Animation Studios', 2),
('JM Animation', 2),
('Japan Vistec', 3),
('Jichitai Anime', 2),
('Jiman Wenhua', 2),
('Jinnan Studio', 2),
('Jinnis Animation Studios', 5),
('Joicy Studio', 2),
('Joker Films', 3),
('Jumondou', 3),
('Jumonji', 4),
('K-Factory', 3),
('KAGAYA Studio', 3),
('KIZAWA Studio', 2),
('KOO-KI', 4),
('KSS', 4),
('KWANED', 2),
('KaKa Technology Studio', 2),
('Kaca Entertainment', 2),
('Kachidoki Studio', 5),
('Kachigarasu', 2),
('Kaeruotoko Shokai', 2),
('Kagome Company', 2),
('Kamikaze Douga', 5),
('Kamio Japan', 2),
('Kanaban Graphics', 5),
('Kaname Productions', 4),
('Karaku', 2),
('Karasfilms', 2),
('Kassen', 2),
('Kate Arrow', 5),
('Kazami Gakuen Koushiki Douga-bu', 2),
('Ke Yue Xue Zi', 2),
('Keica', 2),
('Kenji Studio', 3),
('Kent House', 2),
('KeyEast', 2),
('Keyring', 4),
('Khaki', 3),
('Khara', 5),
('Kid+Kid Animation Studio', 2),
('Kigumi', 2),
('Kinema Citrus', 5),
('Kino Production', 2),
('Kitchen Ltd.', 2),
('Kitty Film Mitaka Studio', 5),
('Knack Productions', 5),
('Kobito', 2),
('Koinrush Studio', 4),
('Kojiro Shishido Animation Works', 3),
('Kokusai Eigasha', 3),
('Konami animation', 3),
('Kuai Ying Hu Yu', 3),
('Kumarba', 2),
('Kung Fu Frog Animation', 4),
('Kuri Jikken Manga Koubou', 5),
('Kyoto Animation', 5),
('Kyotoma', 3),
('LAN Studio', 5),
('LB Commerce', 3),
('LICO', 5),
('LIDENFILMS', 5),
('LIGHTAIR Inc.', 3),
('LMD', 3),
('LX Animation Studio', 4),
('Lan Ying Yingshi', 2),
('LandQ studios', 5),
('Lapin Track', 5),
('Larx Entertainment', 4),
('Lay-duce', 5),
('Le-joy Animation Studio', 2),
('Left Pocket Studio', 2),
('Lerche', 5),
('Lesprit', 5),
('Liber', 3),
('Liberty Animation Studio', 5),
('Lide', 2),
('Life Work', 3),
('Light Chaser Animation Studios', 5),
('LinQ', 2),
('Lingsanwu Animation', 3),
('Live2D Creative Studio', 3),
('Liyu Culture', 3),
('Locus Corporation', 3),
('Long Zhi Gu Wenhua', 2),
('Lyrics', 3),
('L²Studio', 5),
('M.S.C', 5),
('MAINCONCEPT', 2),
('MAPPA', 5),
('MARK', 2),
('MASTER LIGHTS', 2),
('MAT', 2),
('MI', 2),
('MK Pictures', 2),
('MMDGP', 3),
('MMT Technology', 2),
('MOJO Animation', 2),
('MORIE Inc.', 3),
('Mad Box', 2),
('Madhouse', 5),
('Magia Doraglier', 2),
('Magic Bus', 5),
('Magma Studio', 2),
('Maho Film', 5),
('Maikaze', 2),
('Mainichi Eigasha', 2),
('Makaria', 3),
('Making Animation', 4),
('Makino Production', 3),
('Manaa Animation', 3),
('Manga Productions', 2),
('Manglobe', 5),
('Manhoo Culture', 2),
('Manpuku Jinja', 2),
('Marine Entertainment', 2),
('Maro Studio', 2),
('Marone', 2),
('Maru Animation', 2),
('Marui Group', 2),
('Marvelous Entertainment', 2),
('Marvy Jack', 5),
('Marza Animation Planet', 5),
('Maxilla', 4),
('Medo', 2),
('Meruhensha', 3),
('Mili Pictures', 4),
('Milky Cartoon', 4),
('Millepensee', 5),
('Million Volt', 3),
('Mimoid', 5),
('Minakata Laboratory', 4),
('Minami Machi Bugyousho', 3),
('Miota', 3),
('Mippei Eigeki Kiryuukan', 2),
('Mirai Film', 5),
('Mirai Fusion', 2),
('Misogo Animation Studio', 2),
('Miyajima Film', 3),
('Miyu Productions', 4),
('Mokai Technology', 3),
('Monster''s Egg', 3),
('MontBlanc Pictures', 3),
('MooGoo', 3),
('Mook Animation', 3),
('Mook DLE', 2),
('Moss Design Unit', 2),
('Motion Magic', 5),
('Movic', 2),
('Mushi Production', 5),
('N&G Production', 2),
('NANON CREATIVE', 2),
('NAZ', 5),
('NHK', 2),
('NHK Art', 3),
('NHK Enterprises', 3),
('Nagomi', 2),
('Nakamura Production', 2),
('Namu Animation', 2),
('Neft Film', 2),
('Nekonigashi Inc.', 2),
('Network Kouenji Studio', 2),
('New Deer', 4),
('Next Media Animation', 5),
('Nexus', 5),
('Niceboat Animation', 5),
('Nichicaline', 2),
('Nihon Ad Systems', 2),
('Nihon Hoso Eigasha', 3),
('Nippon Animation', 5),
('Nippon Columbia', 2),
('Nippon Ramayana Film', 2),
('Nippon TV Douga', 3),
('No Side', 3),
('Nomad', 5),
('Noovo', 4),
('Nostalook', 4),
('Nothing New', 2),
('Nulls Design', 2),
('Number 19 Animation', 2),
('Nut', 5),
('Nyan Pollution', 2),
('OB Planning', 2),
('OLM', 5),
('OLM Digital', 5),
('ONIRO', 2),
('ORCEN', 2),
('ORENDA', 2),
('OSROCTION', 2),
('OTOIRO', 5),
('OZ', 2),
('Ocon Studio', 4),
('October Media', 3),
('Oddjob', 5),
('Odolttogi', 2),
('Office AO', 3),
('Office Academy', 4),
('Office DCI', 2),
('Office No. 8', 2),
('Office Nobu', 2),
('Oh! Production', 4),
('Okuruto Noboru', 5),
('Olive Studio', 4),
('Onionskin', 5),
('Opera House', 4),
('Orange', 5),
('Ordet', 5),
('Oriental Creative Color', 5),
('Origin', 2),
('Original Force', 5),
('Otogi Production', 4),
('OutSide Directors Company', 2),
('Outline', 3),
('Oxybot', 3),
('Oyster', 2),
('P.A. Works', 5),
('P.I.C.S.', 5),
('PERIMETRON', 5),
('PHANTOM', 2),
('PINE JAM', 5),
('PONOS Corporation', 2),
('PP Project', 3),
('PPM', 3),
('PRA', 5),
('Painted Blade Studio', 2),
('Painting Dream', 5),
('Palm Studio', 4),
('Pancake', 2),
('Panda Factory', 3),
('Panda Tower Studio', 2),
('Panmedia', 2),
('Paper Animation', 2),
('Paper Plane Animation Studio', 3),
('Particlefield', 3),
('Passion Paint Animation', 3),
('Passione', 5),
('Pastel', 5),
('Pb Animation', 4),
('Pepper Conpanna', 2),
('Phoenix Entertainment', 4),
('Picograph', 2),
('Picona', 2),
('Picture Magic', 5),
('Pie in the sky', 5),
('Pierrot Films', 4),
('Pierrot Plus', 5),
('Piso Studio', 5),
('Planet', 4),
('Planet Cartoon', 2),
('Planet Nemo Animation', 2),
('Platinum Vision', 5),
('Plum', 5),
('Plus Heads', 2),
('Pmats9 studio', 4),
('Point Pictures', 3),
('Pollyanna Graphics', 3),
('Polygon Magic', 2),
('Polygon Pictures', 5),
('Poncotan', 3),
('Pony Canyon', 2),
('Pops Inc.', 4),
('Primastea', 2),
('PrimeTime', 4),
('Production +h.', 4),
('Production GoodBook', 2),
('Production HASU', 3),
('Production I.G', 5),
('Production IMS', 5),
('Production Reed', 5),
('Production Wave', 2),
('Project No.9', 5),
('Project Studio Q', 3),
('Project Team Argos', 4),
('Project Team Eikyuu Kikan', 2),
('Project Team Sarah', 3),
('Psyde Kick Studio', 2),
('Public & Basic', 3),
('Purple Cow Studio Japan', 3),
('Puzzle Animation Studio Limited', 4),
('Qianqi Animation', 3),
('Qingkong Qian Li', 3),
('Qingxiang Culture', 5),
('Qiying Animation', 2),
('Qiyuan Yinghua', 4),
('Quad', 4),
('Qualia Animation', 3),
('Qubic Pictures', 2),
('Quebico', 2),
('Quyue Technology', 2),
('Qzil.la', 5),
('R11R', 3),
('RAMS', 2),
('REALTHING', 2),
('RG Animation Studios', 5),
('ROLL2', 3),
('Rabbit Machine', 3),
('Radix', 5),
('Raiose', 2),
('Red Dog Culture House', 5),
('Reiki Eyes Animation', 3),
('Reirs', 2),
('Remic', 3),
('Revoroot', 4),
('Rhythmos', 2),
('Rikuentai', 4),
('Ripple Film', 2),
('Ripromo', 2),
('Rising Force', 4),
('Robot Communications', 5),
('Rocen', 5),
('Rock''n Roll Mountain', 2),
('Rockwell Eyes', 2),
('Romanov Films', 2),
('Rouseact', 2),
('Ruo Hong Culture', 5),
('S.o.K', 3),
('SAFEHOUSE', 2),
('SAMG Entertainment', 5),
('SANZIGEN', 5),
('SBS TV Production', 2),
('SEK Studios', 4),
('SIDO LIMITED', 3),
('SIGNIF', 3),
('SILVER LINK.', 5),
('SJYNEXCUS', 2),
('SPEED', 2),
('STUDIO 8 DOGS', 3),
('STUDIO6''oN', 2),
('STUDIOK110', 5),
('Saber Project', 2),
('Saber Works', 2),
('Saetta', 4),
('Saigo no Shudan', 5),
('Sakura Create', 3),
('Samsara Animation Studio', 3),
('San-X', 2),
('Sanctuary', 2),
('Sanjie Donghua', 2),
('Sankaku', 2),
('Sanrio', 3),
('Sanrio Digital', 2),
('Sasayuri', 2),
('Satelight', 5),
('Science SARU', 5),
('Scooter Films', 5),
('Seasun Pictures', 2),
('Seoul Movie', 2),
('Seven', 5),
('Seven Arcs', 5),
('Seven Arcs Pictures', 5),
('Seven Stone Entertainment', 4),
('Shadow Pond Studio', 3),
('Shadow Steps', 2),
('Shaft', 5),
('Shanghai Animation Film Studio', 5),
('Shanghai Hippo Animation', 4),
('Shanghai Zhijian Network', 2),
('Sharefun Studio', 4),
('Shelty', 2),
('Shengguang Knight Culture', 2),
('Shengying Animation', 5),
('Shenli Guangyin', 2),
('Shenman Entertainment', 5),
('Shimogumi', 4),
('Shin-Ei Animation', 5),
('Shinkuukan', 2),
('Shirogumi', 5),
('Shochiku Animation Institute', 4),
('Shogakukan Music & Digital Entertainment', 5),
('Shogakukan-Shueisha Productions', 2),
('Shou Fan Yu Shu Gongzuoshi', 2),
('Shueisha', 2),
('Shuiniu Dongman', 3),
('Shuka', 5),
('Shykeumo Animation Studio', 3),
('Signal.MD', 5),
('Silver', 4),
('Skyloong', 2),
('Slow Studio', 4),
('Soeishinsha', 2),
('Sofix', 2),
('Soft Garage', 2),
('Soigne', 2),
('Sola Digital Arts', 5),
('Sotsu', 3),
('Soul Creative', 2),
('Sovat Theater', 2),
('Soyuzmultfilm', 2),
('Space Neko Company', 4),
('Sparkly Key Animation Studio', 5),
('Sparky Animation', 2),
('Speed Inc.', 2),
('Spell Bound', 2),
('Spooky graphic', 3),
('Spoon', 2),
('Sprite Animation Studios', 3),
('Square Enix Visual Works', 3),
('Square Pictures', 2),
('Staple Entertainment', 4),
('StarLink', 2),
('Starry Cube', 2),
('StealthWorks', 2),
('Steamworks', 4),
('Stellar Pictures', 3),
('Stereotype', 4),
('Steve N'' Steven', 4),
('Stingray', 3),
('Story Effect', 2),
('StoryRiders Co. Ltd.', 2),
('Strawberry Meets Pictures', 2),
('Studio 3Hz', 5),
('Studio 4°C', 5),
('Studio 88', 3),
('Studio A-CAT', 5),
('Studio A. Craft', 3),
('Studio Add', 2),
('Studio Animal', 5),
('Studio BAZOOKA', 5),
('Studio BETTA', 2),
('Studio Barcelona', 4),
('Studio Bind', 5),
('Studio Bingo', 3),
('Studio Binzo', 5),
('Studio Blanc.', 5),
('Studio Bogey', 3),
('Studio Button', 2),
('Studio CANDY BOX', 4),
('Studio Chizu', 4),
('Studio Chromato', 2),
('Studio Clutch', 2),
('Studio Coa', 2),
('Studio Cockpit', 2),
('Studio Colorido', 5),
('Studio Comet', 5),
('Studio Core', 2),
('Studio Crocodile', 4),
('Studio Curtain', 2),
('Studio D-Volt', 2),
('Studio DURIAN', 3),
('Studio Dadashow', 4),
('Studio Daisy', 3),
('Studio Deen', 5),
('Studio Dotou', 2),
('Studio Egg', 3),
('Studio Eight Color', 2),
('Studio Elle', 4),
('Studio Fantasia', 5),
('Studio Flad', 4),
('Studio Flag', 3),
('Studio Fusion', 2),
('Studio G-1Neo', 2),
('Studio G7', 2),
('Studio GOONEYS', 3),
('Studio Gale', 5),
('Studio Gazelle', 3),
('Studio Ghibli', 5),
('Studio Gohan', 5),
('Studio Goindol', 2),
('Studio Gokumi', 5),
('Studio Gram', 2),
('Studio Graph77', 2),
('Studio Guts', 2),
('Studio HUIT', 2),
('Studio Hakk', 2),
('Studio Harutonari', 2),
('Studio Hibari', 5),
('Studio Himalaya', 2),
('Studio Hokiboshi', 2),
('Studio Izena', 2),
('Studio Jemi', 5),
('Studio Junio', 5),
('Studio KAI', 5),
('Studio Kafka', 3),
('Studio Kajino', 3),
('Studio KeepFire', 2),
('Studio Kelmadick', 2),
('Studio Khronos', 2),
('Studio Kikan', 5),
('Studio Kingyoiro', 3),
('Studio Korumi', 2),
('Studio Kyuuma', 3),
('Studio Lemon', 2),
('Studio Lings', 3),
('Studio Live', 5),
('Studio M2', 3),
('Studio March', 2),
('Studio Massket', 4),
('Studio Matomo', 2),
('Studio Matrix', 3),
('Studio Maybe', 2),
('Studio Meditation With a Pencil', 4),
('Studio Mir', 2),
('Studio Moe', 3),
('Studio Moriken', 4),
('Studio N', 3),
('Studio Nanahoshi', 5),
('Studio Nuck', 2),
('Studio OX', 3),
('Studio Outrigger', 2),
('Studio Palette', 4),
('Studio Pastoral', 3),
('Studio Pierrot', 5),
('Studio Pivote', 4),
('Studio Placebo', 5),
('Studio Polon', 2),
('Studio Ponoc', 3),
('Studio Ppuri', 2),
('Studio PuYUKAI', 5),
('Studio Ranmaru', 3),
('Studio Rikka', 4),
('Studio Shelter', 2),
('Studio Sign', 4),
('Studio Signal', 4),
('Studio Signpost', 4),
('Studio Sota', 2),
('Studio Take Off', 2),
('Studio Tron', 2),
('Studio Tumble', 3),
('Studio UGOKI', 2),
('Studio Unicorn', 3),
('Studio VOLN', 5),
('Studio Vandal', 2),
('Studio W.Baba', 2),
('Studio World', 2),
('Studio Yona', 4),
('Studio Z5', 2),
('Studio Zero', 3),
('Studio! Cucuri', 2),
('StudioRF Inc.', 2),
('StudioXD', 3),
('Sublimation', 3),
('Success Corp.', 3),
('Sugata Creative & Design', 4),
('Suna Kouhou', 2),
('Sunflowers', 4),
('Sunny Gapen', 2),
('Sunrise', 5),
('Sunrise Beyond', 4),
('Sunshine Corporation', 2),
('Sunwoo Entertainment', 2),
('Suoyi Technology', 5),
('Super Brain', 2),
('Super Normal Studio', 4),
('Suspenders', 3),
('Synergy Japan', 3),
('SynergySP', 5),
('T.P.O', 2),
('TANOsim', 2),
('TCJ', 5),
('THINGS.', 2),
('THINKR', 4),
('THREE IS A MAGIC NUMBER', 3),
('TMS Entertainment', 5),
('TNK', 5),
('TOCSIS', 2),
('TOHO animation', 2),
('TOHO animation STUDIO', 5),
('TROYCA', 5),
('TUBA', 4),
('TV Douga', 4),
('TYMOTE', 2),
('TYO Animations', 5),
('Taiko Studios', 2),
('Taikong Works', 3),
('Takahashi Studio', 4),
('Takara Tomy A.R.T.S', 2),
('Takun Manga Box', 5),
('Tama Production', 2),
('Tang Cai Zhaopin', 2),
('Tang Kirin Culture', 4),
('Taomee', 3),
('Tatsunoko Production', 5),
('Team OneOne', 2),
('Team TillDawn', 2),
('Team YokkyuFuman', 4),
('Tear Studio', 3),
('Tecarat', 5),
('Teddy', 2),
('Telecom Animation Film', 5),
('Teleimage', 2),
('Telescreen', 4),
('Ten Tails Animation', 2),
('Tengu Kobo', 3),
('Tezuka Productions', 5),
('The Answer Studio', 5),
('The Monk Studios', 2),
('The Village of Marchen', 2),
('Three-d', 3),
('Thundray', 5),
('Tianshi Wenhua', 3),
('Tiao Tiao Tang Donghua', 2),
('Tochka', 3),
('Toei Animation', 5),
('Toei Video', 2),
('Toho Interactive Animation', 4),
('Tokyo Kids', 5),
('Tokyo Media Connections', 2),
('Tokyo Movie', 5),
('Tokyo Movie Shinsha', 5),
('Tokyo TV Douga', 3),
('Tomason', 3),
('Tomovies', 4),
('Tomoyasu Murata Company', 5),
('Tonari Animation', 2),
('Tong Mingxuan Studio', 3),
('Tonko House', 2),
('Toon Harbor Works', 3),
('Topcraft', 4),
('Toyo Links Corporation', 2),
('Trans Arts', 5),
('Transcendence Picture', 5),
('Transistor Studio', 3),
('Trash Studio', 5),
('Tri-Slash', 2),
('TriF Studio', 4),
('Triangle Staff', 5),
('Trigger', 5),
('Trinet Entertainment', 5),
('TrioPen Studio', 4),
('Triple A', 2),
('Tsubasa Production', 2),
('Tsuburaya Productions', 3),
('Tsuchida Productions', 5),
('Tsukimidou', 2),
('Tsumugi Akita Animation Lab', 3),
('Tsumupapa', 2),
('TthunDer Animation', 2),
('Twilight Studio', 2),
('Twilight Town', 2),
('Twin Engine', 2),
('TypeZero', 2),
('Typhoon Graphics', 5),
('UKA', 4),
('UWAN Pictures', 4),
('UchuPeople', 2),
('Uguisu Kobo', 4),
('Ultra Super Pictures', 3),
('Unend', 2),
('Urban Product', 3),
('Usagi Ou', 5),
('V-sign', 2),
('VAP', 2),
('VCRWORKS', 5),
('VROOOOM', 2),
('Vasoon Animation', 3),
('Vega Entertainment', 5),
('Venet', 4),
('Viewworks', 3),
('Village Studio', 3),
('Visual 80', 5),
('Visual Flight', 2),
('Voil', 3),
('Volca', 3),
('W+K Tokyo', 2),
('W-Toon Studio', 5),
('WAO World', 5),
('WHOPPERS', 2),
('Wako Production', 4),
('Wang Film Productions', 2),
('Watanabe Promotion', 2),
('Wawayu Animation', 5),
('Wei Chuang Jiang Xin', 2),
('Welz Animation Studios', 2),
('Whatever', 2),
('White Fox', 5),
('Will Palette', 2),
('Windy Studio', 3),
('Wit Studio', 5),
('Wolf Smoke Studio', 3),
('Wolfsbane', 3),
('Wonder Cat Animation', 5),
('WonderLand', 2),
('Wong Ping Animation Lab', 4),
('Woodpecker', 2),
('Wulifang', 3),
('XEBEC M2', 3),
('XFLAG', 2),
('XFLAG Pictures', 3),
('Xanthus Media', 2),
('Xebec', 5),
('Xiaoming Taiji', 3),
('Xing Xing Donghua', 2),
('Xing Yi Kai Chen', 5),
('Xuni Ying Ye', 3),
('YHKT Entertainment', 5),
('YURUPPE Inc.', 3),
('Yamamura Animation', 5),
('Yamato Works', 2),
('Yamiken', 3),
('Yaoyorozu', 5),
('Yasuda Genshou Studio by Xenotoon', 2),
('Year Young Culture', 3),
('Yi Chen Animation', 4),
('Yien Animation Studio', 5),
('Yinhe Changxing Culture', 3),
('Yokohama Animation Lab', 5),
('Yonago Gainax', 2),
('Yostar Pictures', 5),
('Youku', 2),
('Youliao Studio', 2),
('Yudubai Animation', 3),
('Yuhodo', 2),
('Yumao Wenhua', 2),
('Yumeta Company', 5),
('Zelico Film', 2),
('Zero-G', 5),
('Zero-G Room', 4),
('Zexcs', 5),
('Zhou Ling Wenhua', 2),
('Ziine Studio', 2),
('Zuiyo', 3),
('aNCHOR', 2),
('ame pippin', 2),
('animate Film', 5),
('animation studio42', 2),
('asread.', 5),
('asurafilm', 5),
('bushes', 2),
('cogitoworks', 3),
('d00r works', 3),
('domerica', 5),
('drop', 3),
('dwarf', 5),
('evg', 2),
('feel.', 5),
('flag Co.', 2),
('foodunited.', 2),
('happyproject', 2),
('helo.inc', 2),
('iDRAGONS Creative Studio', 3),
('indigo line', 2),
('l-a-unch・BOX', 3),
('lxtl', 3),
('maroyaka', 2),
('miHoYoAnime', 3),
('mico.animation', 2),
('monofilmo', 4),
('pH Studio', 5),
('production doA', 3),
('qmotri', 5),
('soket', 2),
('studio ALBLE', 2),
('studio MOTHER', 5),
('studio NAGURI', 2),
('studio YOG', 3),
('studio hb', 2),
('studio maf', 2),
('studio2 Animation Lab', 2),
('studioDOT', 2),
('sugarsaltpepper', 2),
('team Yamahitsuji', 3),
('teamKG', 3),
('teevee graphics', 3),
('trenova', 3),
('ufotable', 5),
('uzupiyo Animation & Digital Works', 2),
('yell', 3);
