import requests
import random
import time
from tqdm import tqdm
import os

# Import necessary libraries for API requests, random operations, time delays, progress bars, and file system operations.

# Studio name to StudioID mapping (based on your list)
# This dictionary maps studio names fetched from the API to their corresponding numerical IDs in the database.
studio_map = {
    '100studio': 1,
    '10Gauge': 2,
    '1IN': 3,
    '2:10 Animation': 4,
    '33 Collective': 5,
    '3D Co.': 6,
    '5 Inc.': 7,
    '6pucks': 8,
    '717 Animation Studio': 9,
    '7doc': 10,
    '81 Produce': 11,
    '8bit': 12,
    '924 Studio': 13,
    'A-1 Pictures': 14,
    'A-Line': 15,
    'A-Real': 16,
    'A.C.G.T.': 17,
    'A4A Inc.': 18,
    'ABJ COMPANY': 19,
    'ACC Production': 20,
    'ACiD FiLM': 21,
    'AHA Entertainment': 22,
    'AIC': 23,
    'AIC ASTA': 24,
    'AIC Build': 25,
    'AIC Classic': 26,
    'AIC Frontier': 27,
    'AIC PLUS+': 28,
    'AIC Project': 29,
    'AIC Spirits': 30,
    'AIC Takarazuka': 31,
    'AION Studio': 32,
    'ANIDO FILM': 33,
    'ANYZAC': 34,
    'AOI Pro.': 35,
    'APPP': 36,
    'AQUA ARIS': 37,
    'ARCUS': 38,
    'ARECT': 39,
    'ASK Animation Studio': 40,
    'ASTROBROS.': 41,
    'AXsiZ': 42,
    'AYCO': 43,
    'Academy Productions': 44,
    'Acca effe': 45,
    'Actas': 46,
    'Adonero': 47,
    'Aeonium': 48,
    'Agent 21': 49,
    'Ai Si Animation Studio': 50,
    'Ajia-do': 51,
    'Akatsuki': 52,
    'Albacrow': 53,
    'Alfred Imageworks': 54,
    'Alke': 55,
    'Alpha Animation': 56,
    'Alpha Group': 57,
    'Amineworks': 58,
    'An DerCen': 59,
    'Andraft': 60,
    'Angle': 61,
    'Anima': 62,
    'Anima&Co.': 63,
    'Animaruya': 64,
    'Animation 21': 65,
    'Animation 501': 66,
    'Animation Do': 67,
    'Animation Lab Japan': 68,
    'Animation Planet': 69,
    'Animation Staff Room': 70,
    'Animation Studio Wagumi': 71,
    'Anime Beans': 72,
    'Anime R': 73,
    'Anime Tokyo': 74,
    'Ankama Animations': 75,
    'Annapuru': 76,
    'Anon Pictures': 77,
    'Anpro': 78,
    'Arch': 79,
    'Arcs Create': 80,
    'Arcturus': 81,
    'Arms': 82,
    'Artland': 83,
    'Artmic': 84,
    'Artner': 85,
    'Arvo Animation': 86,
    'Asahi Production': 87,
    'Ascension': 88,
    'Ashi Productions': 89,
    'Asmik Ace': 90,
    'Assez Finaud Fabric': 91,
    'Asura Film': 92,
    'Atelier Pontdarc': 93,
    'Atelier Tuki': 94,
    'Au Praxinoscope': 95,
    'Aubec': 96,
    'Aurochs': 97,
    'Aurora Animation': 98,
    'Aurum Production': 99,
    'Automatic Flowers Studio': 100,
    'Avaco Creative Studios': 101,
    'Axis': 102,
    'Azeta Pictures': 103,
    'B&T': 104,
    'B.CMAY PICTURES': 105,
    'BUDDHA INC.': 106,
    'BUG FILMS': 107,
    'BUILD DREAM': 108,
    'BYMENT': 109,
    'Bakken Record': 110,
    'Bandai Namco Filmworks': 111,
    'Bandai Namco Pictures': 112,
    'Barnum Studio': 113,
    'BeSTACK': 114,
    'Beat Frog': 115,
    'Bebow': 116,
    'Bee Media': 117,
    'Bee Train': 118,
    'Beijing Enlight Pictures': 119,
    'Beijing Huihuang Animation Company': 120,
    'Bellnox Films': 121,
    'Benlai Pictures': 122,
    'Bibury Animation CG': 123,
    'Bibury Animation Studios': 124,
    'Big Bang': 125,
    'Big Firebird Culture': 126,
    'Big Pine Animation Studio': 127,
    'Bigcat Studio': 128,
    'Blade': 129,
    'Blaze Studio': 130,
    'BloomZ': 131,
    'Blue bread': 132,
    'BlueArc Animation Studios': 133,
    'Bones': 134,
    'Bones Film': 135,
    'Borutong': 136,
    'Bouncy': 137,
    'Boyan Pictures': 138,
    "Brain's Base": 139,
    'Brians Film': 140,
    'Brick Studio': 141,
    'Bridge': 142,
    'Brio Animation': 143,
    'Buemon': 144,
    'Buyuu': 145,
    'C-Station': 146,
    'C2C': 147,
    'CANON RECORDINGS': 148,
    'CANOPUS': 149,
    'CCTV Animation Group': 150,
    'CELAVIE': 151,
    'CG Year': 152,
    'CGCG Studio': 153,
    'CHOCOLATE': 154,
    'CLAP': 155,
    'CMAY Animation': 156,
    'CMC Media': 157,
    'CUCURI': 158,
    'CUEBiC Inc.': 159,
    'Calf Studio': 160,
    'Caviar': 161,
    'Central Animation Studio': 162,
    'Chaos Project': 163,
    'Charaction': 164,
    'Children''s Playground Entertainment': 165,
    'Chiptune': 166,
    'Chongzhuo Animation': 167,
    'Chosen': 168,
    'CinePix': 169,
    'Circus Production': 170,
    'Cloud Art': 171,
    'Cloud Culture': 172,
    'Cloud Hearts': 173,
    'CloverWorks': 174,
    'CoMix Wave Films': 175,
    'Coastline Animation Studio': 176,
    'Cocktail Media': 177,
    'Code': 178,
    'Colored Pencil Animation': 179,
    'Colored Pencil Animation Japan': 180,
    'Comma Studio': 181,
    'CompTown': 182,
    'Composition Inc.': 183,
    'Congrong Film': 184,
    'Connect': 185,
    'Contrail': 186,
    'Craftar Studios': 187,
    'Creative House Pocket': 188,
    'Creative Power Entertaining': 189,
    'Creators Dot Com': 190,
    'Creators in Pack': 191,
    'Creatures Inc.': 192,
    'Crew-Cell': 193,
    'CyberConnect2': 194,
    'Cyclone Graphics': 195,
    'CygamesPictures': 196,
    'D & D Pictures': 197,
    'D''ART Shtajio': 198,
    'D.A.S.T Corporation': 199,
    'DAX Production': 200,
    'DC Impression Vision': 201,
    'DEFT': 202,
    'DLE': 203,
    'DMM.futureworks': 204,
    'DOGA Productions': 205,
    'DR Movie': 206,
    'DRAWIZ': 207,
    'Daewon Media': 208,
    'Dai-Ichi Douga': 209,
    'Dancing CG Studio': 210,
    'DandeLion Animation Studio': 211,
    'Dangun Pictures': 212,
    'Darts': 213,
    'Daume': 214,
    'David Production': 215,
    'Dawn Animation': 216,
    'Dazzling Star': 217,
    'Deck': 218,
    'Decovocal': 219,
    'Delight Animation': 220,
    'Delpic': 221,
    'Digital Dream Studios': 222,
    'Digital Frontier': 223,
    'Digital Media Lab': 224,
    'Digital Network Animation': 225,
    'Diomedéa': 226,
    'Directions': 227,
    'Djinn Power': 228,
    'Doga Kobo': 229,
    'Dongwoo A&E': 230,
    'Drawing and Manual': 231,
    'Drive': 232,
    'Durandal': 233,
    'Durufix': 234,
    'Dyna Method': 235,
    'Dynamic Planning': 236,
    'Dynamo Pictures': 237,
    'E&G Films': 238,
    'E&H Production': 239,
    'EDP graphic works': 240,
    'EKACHI EPILKA': 241,
    'EMT Squared': 242,
    'ENGI': 243,
    'EOTA': 244,
    'Eallin': 245,
    'Earth Design Works': 246,
    'East Fish Studio': 247,
    'Echoes': 248,
    'Egg': 249,
    'Egg Firm': 250,
    'Eiken': 251,
    'Ekakiya': 252,
    'Ekura Animal': 253,
    'Elias': 254,
    'Emon': 255,
    'Encourage Films': 256,
    'Enishiya': 257,
    'Enjin Productions': 258,
    'Escape Velocity Animation': 259,
    'Euluca Lab': 260,
    'Ezόla': 261,
    'FAB': 262,
    'FILMONY': 263,
    'FIREBUG': 264,
    'FOREST Hunting One': 265,
    'FUNNY MOVIE': 266,
    'Fantawild Animation': 267,
    'Fanworks': 268,
    'Felix Film': 269,
    'Fengyun Animation': 270,
    'Fenz': 271,
    'Fever Creations': 272,
    'Fifth Avenue': 273,
    'Filmlink International': 274,
    'Flagship Line': 275,
    'Flat Studio': 276,
    'Flint Sugar': 277,
    'Flying Monkeys Production': 278,
    'Flying Ship Studio': 279,
    'Foch Film': 280,
    'Fortes': 281,
    'Four Some': 282,
    'Friendly Land': 283,
    'Front Line': 284,
    'Front Wing': 285,
    'Frontier One': 286,
    'Frontier Works': 287,
    'Fugaku': 288,
    'Fuji TV': 289,
    'Fukushima Gaina': 290,
    'Future Planet': 291,
    'G&G Direction': 292,
    'G&G Entertainment': 293,
    'G-angle': 294,
    'GANSIS': 295,
    'GARDEN Culture': 296,
    'GARDEN LODGE': 297,
    'GEMBA': 298,
    'GIFTanimation': 299,
    'GRIZZLY': 300,
    'GUMBLAB': 301,
    'Ga-Crew': 302,
    'Gaina': 303,
    'Gainax': 304,
    'Gainax Kyoto': 305,
    'Gakken': 306,
    'Gakken Eigakyoku': 307,
    'Gallop': 308,
    'Gambit': 309,
    'Garyuu Studio': 310,
    'Gathering': 311,
    'Gear Studio': 312,
    'Geek Toys': 313,
    'Gekkou': 314,
    'Genco': 315,
    'General Entertainment': 316,
    'Geno Studio': 317,
    'Giga Production': 318,
    'Ginga Teikoku': 319,
    'Ginga Ya': 320,
    'GoHands': 321,
    'Gonzino': 322,
    'Gonzo': 323,
    'Gosay Studio': 324,
    'Goto Inc.': 325,
    'Graphinica': 326,
    'Gravity Well': 327,
    'Grayscale Arts': 328,
    'Green Monster Team': 329,
    'Griot Groove': 330,
    'Grom': 331,
    'Group Creato': 332,
    'Group TAC': 333,
    'Grouper Productions': 334,
    'Guo Pengzi Studio': 335,
    'Guton Animation Studio': 336,
    'Gyorai Eizo Inc.': 337,
    'HAL Film Maker': 338,
    'HIDEHOMARE': 339,
    'HM Heros': 340,
    'HMCH': 341,
    'HORNETS': 342,
    'HOTZIPANG': 343,
    'HS Pictures Studio': 344,
    'Hai An Xian Donghua Gongzuo Shi': 345,
    'Hananona Studio': 346,
    'Hand to Mouse.': 347,
    'Haneda xR Studio': 348,
    'Hanho Heung-Up': 349,
    'Haoliners Animation League': 350,
    'Happy Elements': 351,
    'Hayabusa Film': 352,
    'HeART-BIT': 353,
    'Heart & Soul Animation': 354,
    'Heewon Entertainment': 355,
    'Hero': 356,
    'Hezmon Animation': 357,
    'Hifumi': 358,
    'Higashinaka Studio': 359,
    'High Energy Studio': 360,
    'Hiro Media': 361,
    'Hololive Production': 362,
    'Hong Ying Animation': 363,
    'Hoods Entertainment': 364,
    'Horannabi': 365,
    'HoriPro': 366,
    'Hotline': 367,
    'Hu Po Donghua': 368,
    'HuaDream': 369,
    'HuaMei Animation': 370,
    'Hurray!': 371,
    'Husio Studio': 372,
    'Hutoon Animation': 373,
    'I & A': 374,
    'I was a Ballerina': 375,
    'I-move': 376,
    'I.Gzwei': 377,
    'I.Toon': 378,
    'ILCA': 379,
    'ILCASHIPS': 380,
    'IMAGICA Lab.': 381,
    'INTERFACEDOGS': 382,
    'Ice Butter': 383,
    'Iconix Entertainment': 384,
    'Idea Factory': 385,
    'Idol': 386,
    'Ijigen Tokyo': 387,
    'Image Kei': 388,
    'Image Studio 109': 389,
    'Imagestone Inc.': 390,
    'Imageworks Studio': 391,
    'Imagi': 392,
    'Imagica': 393,
    'Imagica Digitalscape': 394,
    'Imagica Imageworks': 395,
    'Imagica Infos': 396,
    'Imagin': 397,
    'Imagineer': 398,
    'Indeprox': 399,
    'Indivision': 400,
    'Infinity Animations': 401,
    'Infinity Vision': 402,
    'Ishikawa Pro': 403,
    'Ishimori Entertainment': 404,
    'Issen': 405,
    'Itasca Studio': 406,
    'Iyasakadou Film': 407,
    'J.C.F.': 408,
    'J.C.Staff': 409,
    'JCF': 410,
    'JJJOY Animation Studios': 411,
    'JM Animation': 412,
    'Japan Vistec': 413,
    'Jichitai Anime': 414,
    'Jinnan Studio': 415,
    'Jinnis Animation Studios': 416,
    'Joicy Studio': 417,
    'Joker Films': 418,
    'Jumondo': 419,
    'Jumonji': 420,
    'K-Factory': 421,
    'KAGAYA Studio': 422,
    'KIZAWA Studio': 423,
    'KOO-KI': 424,
    'KSS': 425,
    'KWANED': 426,
    'KaKa Technology Studio': 427,
    'Kaca Entertainment': 428,
    'Kachidoki Studio': 429,
    'Kachigarasu': 430,
    'Kaeruotoko Shokai': 431,
    'Kamikaze Douga': 432,
    'Kamio Japan': 433,
    'Kanaban Graphics': 434,
    'Kaname Productions': 435,
    'Karaku': 436,
    'Karasfilms': 437,
    'Kassen': 438,
    'Kate Arrow': 439,
    'Kazami Gakuen Koushiki Douga-bu': 440,
    'Keica': 441,
    'Kenji Studio': 442,
    'Kent House': 443,
    'KeyEast': 444,
    'Keyring': 445,
    'Khaki': 446,
    'Khara': 447,
    'Kigumi': 448,
    'Kinema Citrus': 449,
    'Kino Production': 450,
    'Kitchen Ltd.': 451,
    'Kitty Film Mitaka Studio': 452,
    'Knack Productions': 453,
    'Kobito': 454,
    'Koinrush Studio': 455,
    'Kojiro Shishido Animation Works': 456,
    'Kokusai Eigasha': 457,
    'Konami animation': 458,
    'Kuai Ying Hu Yu': 459,
    'Kumarba': 460,
    'Kung Fu Frog Animation': 461,
    'Kuri Jikken Manga Koubou': 462,
    'Kyoto Animation': 463,
    'Kyotoma': 464,
    'LAN Studio': 465,
    'LB Commerce': 466,
    'LICO': 467,
    'LIDENFILMS': 468,
    'LIGHTAIR Inc.': 469,
    'LMD': 470,
    'LX Animation Studio': 471,
    'Laftel': 472,
    'LandQ studios': 473,
    'Lapin Track': 474,
    'Larx Entertainment': 475,
    'Lay-duce': 476,
    'Le-joy Animation Studio': 477,
    'Lerche': 478,
    'Lesprit': 479,
    'Liber': 480,
    'Liberty Animation Studio': 481,
    'Lide': 482,
    'Life Work': 483,
    'Light Chaser Animation Studios': 484,
    'LinQ': 485,
    'Lingsanwu Animation': 486,
    'Live2D Creative Studio': 487,
    'Liyu Culture': 488,
    'Locus Corporation': 489,
    'Lyrics': 490,
    'L²Studio': 491,
    'M.S.C': 492,
    'MAINCONCEPT': 493,
    'MAPPA': 494,
    'MARK': 495,
    'MASTER LIGHTS': 496,
    'MAT': 497,
    'MI': 498,
    'MK Pictures': 499,
    'MMDGP': 500,
    'MMT Technology': 501,
    'MOJO Animation': 502,
    'MORIE Inc.': 503,
    'Mad Box': 504,
    'Madhouse': 505,
    'Magia Doraglier': 506,
    'Magic Bus': 507,
    'Magma Studio': 508,
    'Maho Film': 509,
    'Mainichi Eigasha': 510,
    'Makaria': 511,
    'Making Animation': 512,
    'Makino Production': 513,
    'Manaa Animation': 514,
    'Manga Productions': 515,
    'Manglobe': 516,
    'Marine Entertainment': 517,
    'Maro Studio': 518,
    'Marone': 519,
    'Maru Animation': 520,
    'Marui Group': 521,
    'Marvelous Entertainment': 522,
    'Marvy Jack': 523,
    'Marza Animation Planet': 524,
    'Maxilla': 525,
    'Media Factory': 526,
    'Medo': 527,
    'Meruhensha': 528,
    'Mili Pictures': 529,
    'Milky Cartoon': 530,
    'Millepensee': 531,
    'Million Volt': 532,
    'Mimoid': 533,
    'Minakata Laboratory': 534,
    'Minami Machi Bugyousho': 535,
    'Miota': 536,
    'Mippei Eigeki Kiryuukan': 537,
    'Mirai Film': 538,
    'Mirai Fusion': 539,
    'Misogo Animation Studio': 540,
    'Miyu Productions': 541,
    'Mokai Technology': 542,
    'Monster''s Egg': 543,
    'MontBlanc Pictures': 544,
    'MooGoo': 545,
    'Mook Animation': 546,
    'Mook DLE': 547,
    'Moss Design Unit': 548,
    'Motion Magic': 549,
    'Movic': 550,
    'Mushi Production': 551,
    'Myung Films': 552,
    'N&G Production': 553,
    'NANON CREATIVE': 554,
    'NAZ': 555,
    'NHK': 556,
    'NHK Art': 557,
    'NHK Enterprises': 558,
    'Nagomi': 559,
    'Nakamura Production': 560,
    'Namu Animation': 561,
    'Neft Film': 562,
    'Nekonigashi Inc.': 563,
    'Network Kouenji Studio': 564,
    'New Deer': 565,
    'Next Media Animation': 566,
    'Nexus': 567,
    'Nice Boat Animation': 568,
    'Nihon Ad Systems': 569,
    'Nihon Hoso Eigasha': 570,
    'Nippon Animation': 571,
    'Nippon Columbia': 572,
    'Nippon Ramayana Film Co.': 573,
    'Nippon TV Douga': 574,
    'No Side': 575,
    'Nomad': 576,
    'Noovo': 577,
    'Nostalook': 578,
    'Nut': 579,
    'OB Planning': 580,
    'OLM': 581,
    'OLM Digital': 582,
    'ONIRO': 583,
    'ORCEN': 584,
    'ORENDA': 585,
    'OTOIRO': 586,
    'OZ': 587,
    'Ocon Studio': 588,
    'October Media': 589,
    'Oddjob': 590,
    'Odolttogi': 591,
    'Office AO': 592,
    'Office DCI': 593,
    'Office No. 8': 594,
    'Office Nobu': 595,
    'Oh! Production': 596,
    'Okuruto Noboru': 597,
    'Olive Studio': 598,
    'Onionskin': 599,
    'Opera House': 600,
    'Orange': 601,
    'Ordet': 602,
    'Oriental Creative Color': 603,
    'Original Force': 604,
    'Otogi Production': 605,
    'OutSide Directors Company': 606,
    'Outline': 607,
    'Oxybot': 608,
    'Oyster': 609,
    'P.A. Works': 610,
    'P.I.C.S.': 611,
    'PERIMETRON': 612,
    'PHANTOM': 613,
    'PINE JAM': 614,
    'PONOS Corporation': 615,
    'PP Project': 616,
    'PPM': 617,
    'PRA': 618,
    'Painted Blade Studio': 619,
    'Painting Dream': 620,
    'Palm Studio': 621,
    'Pancake': 622,
    'Panda Factory': 623,
    'Panda Tower Studio': 624,
    'Panmedia': 625,
    'Paper Animation': 626,
    'Paper Plane Animation Studio': 627,
    'Particlefield': 628,
    'Passion Paint Animation': 629,
    'Passione': 630,
    'Pastel': 631,
    'Pb Animation Co. Ltd.': 632,
    'Phoenix Entertainment': 633,
    'Picograph': 634,
    'Picona': 635,
    'Picture Magic': 636,
    'Pie in the sky': 637,
    'Pierrot': 638,
    'Pierrot Films': 639,
    'Pierrot Plus': 640,
    'Piso Studio': 641,
    'Planet': 642,
    'Planet Cartoon': 643,
    'Planet Nemo Animation': 644,
    'Platinum Vision': 645,
    'Plum': 646,
    'Plus Heads': 647,
    'Pmats9 studio': 648,
    'Point Pictures': 649,
    'Pollyanna Graphics': 650,
    'Polygon Magic': 651,
    'Polygon Pictures': 652,
    'Poncotan': 653,
    'Pony Canyon': 654,
    'Pops Inc.': 655,
    'Primastea': 656,
    'PrimeTime': 657,
    'Production +h.': 658,
    'Production GoodBook': 659,
    'Production HASU': 660,
    'Production I.G': 661,
    'Production IMS': 662,
    'Production Reed': 663,
    'Production Wave': 664,
    'Project No.9': 665,
    'Project Studio Q': 666,
    'Project Team Sarah': 667,
    'Public & Basic': 668,
    'Pure Arts': 669,
    'Purple Cow Studio Japan': 670,
    'Puzzle Animation Studio Limited': 671,
    'Qianqi Animation': 672,
    'Qingxiang Culture': 673,
    'Qiying Animation': 674,
    'Qiyuan Yinghua': 675,
    'Quad': 676,
    'Qualia Animation': 677,
    'Qubic Pictures': 678,
    'Quebico': 679,
    'Quyue Technology': 680,
    'Qzil.la': 681,
    'R11R': 682,
    'RAMS': 683,
    'REALTHING': 684,
    'RG Animation Studios': 685,
    'ROLL2': 686,
    'Rabbit Gate': 687,
    'Rabbit Machine': 688,
    'Radix': 689,
    'Raiose': 690,
    'Red Dog Culture House': 691,
    'Reiki Eyes Animation': 692,
    'Reirs': 693,
    'Remic': 694,
    'Revoroot': 695,
    'Rhythmos': 696,
    'Rikuentai': 697,
    'Ripple Film': 698,
    'Ripromo': 699,
    'Rising Force': 700,
    'Robot Communications': 701,
    'Rocen': 702,
    'Rock''n Roll Mountain': 703,
    'Rockwell Eyes': 704,
    'Romanov Films': 705,
    'Ruo Hong Culture': 706,
    'SAFEHOUSE': 707,
    'SAMG Entertainment': 708,
    'SANZIGEN': 709,
    'SBS TV Production': 710,
    'SEK Studios': 711,
    'SIDO LIMITED': 712,
    'SIGNIF': 713,
    'SILVER LINK.': 714,
    'SJYNEXCUS': 715,
    'SPEED': 716,
    'STUDIO 8 DOGS': 717,
    'STUDIO6''oN': 718,
    'STUDIOK110': 719,
    'Saber Project': 720,
    'Saber Works': 721,
    'Saetta': 722,
    'Saigo no Shudan': 723,
    'Sakura Create': 724,
    'Samsara Animation Studio': 725,
    'San-X': 726,
    'Sanctuary': 727,
    'Sankaku': 728,
    'Sanrio': 729,
    'Sanrio Digital': 730,
    'Sasayuri': 731,
    'Satelight': 732,
    'Science SARU': 733,
    'Scooter Films': 734,
    'Sega Interactive': 735,
    'Seoul Movie': 736,
    'Seven': 737,
    'Seven Arcs': 738,
    'Seven Arcs Pictures': 739,
    'Seven Stone Entertainment': 740,
    'Shadow Pond Studio': 741,
    'Shadow Steps': 742,
    'Shaft': 743,
    'Shanghai Animation Film Studio': 744,
    'Shanghai Hippo Animation': 745,
    'Sharefun Studio': 746,
    'Shelty': 747,
    'Shengguang Knight Culture': 748,
    'Shengying Animation': 749,
    'Shenman Entertainment': 750,
    'Shikachan Studio': 751,
    'Shimogumi': 752,
    'Shin-Ei Animation': 753,
    'Shinkuukan': 754,
    'Shirogumi': 755,
    'Shochiku Animation Institute': 756,
    'Shogakukan Music & Digital Entertainment': 757,
    'Shogakukan-Shueisha Productions': 758,
    'Shueisha': 759,
    'Shuiniu Dongman': 760,
    'Shuka': 761,
    'Shykeumo Animation Studio': 762,
    'Signal.MD': 763,
    'Silver': 764,
    'Slow Studio': 765,
    'Soeishinsha': 766,
    'Sofix': 767,
    'Soft Garage': 768,
    'Soigne': 769,
    'Sola Digital Arts': 770,
    'Sotsu': 771,
    'Sovat Theater': 772,
    'Soyuzmultfilm': 773,
    'Space Neko Company': 774,
    'Sparkly Key Animation Studio': 775,
    'Sparky Animation': 776,
    'Speed Inc.': 777,
    'Spell Bound': 778,
    'Spooky graphic': 779,
    'Spoon': 780,
    'Sprite Animation Studios': 781,
    'Square Enix Visual Works': 782,
    'Square Pictures': 783,
    'Staple Entertainment': 784,
    'Starry Cube': 785,
    'StealthWorks': 786,
    'Steamworks': 787,
    'Stereotype': 788,
    'Steve N'' Steven': 789,
    'Stingray': 790,
    'Story Effect': 791,
    'StoryRiders Co. Ltd.': 792,
    'Strawberry Meets Pictures': 793,
    'Studio 3Hz': 794,
    'Studio 4°C': 795,
    'Studio 88': 796,
    'Studio A-CAT': 797,
    'Studio A. Craft': 798,
    'Studio Add': 799,
    'Studio Animal': 800,
    'Studio Artegg': 801,
    'Studio BAZOOKA': 802,
    'Studio Barcelona': 803,
    'Studio Bind': 804,
    'Studio Bingo': 805,
    'Studio Binzo': 806,
    'Studio Blanc.': 807,
    'Studio Bogey': 808,
    'Studio Button': 809,
    'Studio CANDY BOX': 810,
    'Studio Chizu': 811,
    'Studio Clutch': 812,
    'Studio Coa': 813,
    'Studio Cockpit': 814,
    'Studio Colorido': 815,
    'Studio Comet': 816,
    'Studio Core': 817,
    'Studio Crocodile': 818,
    'Studio D-Volt': 819,
    'Studio DURIAN': 820,
    'Studio Dadashow': 821,
    'Studio Daisy': 822,
    'Studio Deen': 823,
    'Studio Dotou': 824,
    'Studio Egg': 825,
    'Studio Eight Color': 826,
    'Studio Elle': 827,
    'Studio Fantasia': 828,
    'Studio Flad': 829,
    'Studio Flag': 830,
    'Studio Fusion': 831,
    'Studio G-1Neo': 832,
    'Studio GOONEYS': 833,
    'Studio Gale': 834,
    'Studio Gazelle': 835,
    'Studio Ghibli': 836,
    'Studio Gohan': 837,
    'Studio Goindol': 838,
    'Studio Gokumi': 839,
    'Studio Gram': 840,
    'Studio Guts': 841,
    'Studio HUIT': 842,
    'Studio Hakk': 843,
    'Studio Harutonari': 844,
    'Studio Hibari': 845,
    'Studio Himalaya': 846,
    'Studio Hokiboshi': 847,
    'Studio Izena': 848,
    'Studio Jemi': 849,
    'Studio Junio': 850,
    'Studio Kafka': 851,
    'Studio Kai': 852,
    'Studio Kajino': 853,
    'Studio KeepFire': 854,
    'Studio Kelmadick': 855,
    'Studio Khronos': 856,
    'Studio Kikan': 857,
    'Studio Kingyoiro': 858,
    'Studio Korumi': 859,
    'Studio Kyuuma': 860,
    'Studio Lemon': 861,
    'Studio Lings': 862,
    'Studio Live': 863,
    'Studio M2': 864,
    'Studio March': 865,
    'Studio Massket': 866,
    'Studio Matomo': 867,
    'Studio Matrix': 868,
    'Studio Meditation With a Pencil': 869,
    'Studio Mir': 870,
    'Studio Moe': 871,
    'Studio Moriken': 872,
    'Studio N': 873,
    'Studio Nanahoshi': 874,
    'Studio Nuck': 875,
    'Studio OX': 876,
    'Studio Outrigger': 877,
    'Studio Palette': 878,
    'Studio Pastoral': 879,
    'Studio Pivote': 880,
    'Studio Placebo': 881,
    'Studio Polon': 882,
    'Studio Ponoc': 883,
    'Studio Ppuri': 884,
    'Studio PuYUKAI': 885,
    'Studio Ranmaru': 886,
    'Studio Rikka': 887,
    'Studio Shelter': 888,
    'Studio Sign': 889,
    'Studio Signal': 890,
    'Studio Signpost': 891,
    'Studio Sota': 892,
    'Studio Take Off': 893,
    'Studio Tumble': 894,
    'Studio UGOKI': 895,
    'Studio Unicorn': 896,
    'Studio VOLN': 897,
    'Studio Vandal': 898,
    'Studio W.Baba': 899,
    'Studio World': 900,
    'Studio Yona': 901,
    'Studio Z5': 902,
    'Studio Zero': 903,
    'Studio! Cucuri': 904,
    'StudioRF Inc.': 905,
    'StudioXD': 906,
    'Sublimation': 907,
    'Success Corp.': 908,
    'Sugata Creative & Design': 909,
    'Suna Kouhou': 910,
    'Sunflowers': 911,
    'Sunny Gapen': 912,
    'Sunrise': 913,
    'Sunrise Beyond': 914,
    'Sunwoo Entertainment': 915,
    'Suoyi Technology': 916,
    'Super Brain': 917,
    'Super Normal Studio': 918,
    'Suspenders': 919,
    'Synergy Japan': 920,
    'SynergySP': 921,
    'T.P.O': 922,
    'TANOsim': 923,
    'TCJ': 924,
    'THINGS.': 925,
    'THINKR': 926,
    'THREE IS A MAGIC NUMBER': 927,
    'TMS Entertainment': 928,
    'TNK': 929,
    'TOCSIS': 930,
    'TOHO animation': 931,
    'TOHO animation STUDIO': 932,
    'TROYCA': 933,
    'TUBA': 934,
    'TYMOTE': 935,
    'TYO Animations': 936,
    'Taiko Studios': 937,
    'Taikong Works': 938,
    'Takahashi Studio': 939,
    'Takara Tomy A.R.T.S': 940,
    'Takun Manga Box': 941,
    'Tama Production': 942,
    'Tamura Shigeru Studio': 943,
    'Tang Kirin Culture': 944,
    'Taomee': 945,
    'Tatsunoko Production': 946,
    'Team OneOne': 947,
    'Team TillDawn': 948,
    'Team YokkyuFuman': 949,
    'Tear Studio': 950,
    'Tecarat': 951,
    'Teddy': 952,
    'Tele-Cartoon Japan': 953,
    'Telecom Animation Film': 954,
    'Telescreen': 955,
    'Ten Tails Animation': 956,
    'Tengu Kobo': 957,
    'Tezuka Productions': 958,
    'The Answer Studio': 959,
    'The Monk Studios': 960,
    'The Village of Marchen': 961,
    'Think Corporation': 962,
    'Three-d': 963,
    'Thundray': 964,
    'Tianshi Wenhua': 965,
    'Toei Animation': 966,
    'Toei Video': 967,
    'Toho Interactive Animation': 968,
    'Tokyo Kids': 969,
    'Tokyo Media Connections': 970,
    'Tokyo Movie': 971,
    'Tokyo Movie Shinsha': 972,
    'Tokyo TV Douga': 973,
    'Tomason': 974,
    'Tomovies': 975,
    'Tomoyasu Murata Company': 976,
    'Tonari Animation': 977,
    'Tong Ming Xuan': 978,
    'Tonko House': 979,
    'Topcraft': 980,
    'Toyo Links Corporation': 981,
    'Trans Arts': 982,
    'Transcendence Picture': 983,
    'Transistor Studio': 984,
    'Trash Studio': 985,
    'Tri-Slash': 986,
    'TriF Studio': 987,
    'Triangle Staff': 988,
    'Trigger': 989,
    'Trinet Entertainment': 990,
    'TrioPen Studio': 991,
    'Tsuburaya Productions': 992,
    'Tsuchida Productions': 993,
    'Tsukimidou': 994,
    'Tsumugi Akita Animation Lab': 995,
    'Tsumupapa': 996,
    'TthunDer Animation': 997,
    'Twilight Studio': 998,
    'Twilight Town': 999,
    'Twin Engine': 1000,
    'TypeZero': 1001,
    'Typhoon Graphics': 1002,
    'UKA': 1003,
    'UWAN Pictures': 1004,
    'UchuPeople': 1005,
    'Uguisu Kobo': 1006,
    'Ultra Super Pictures': 1007,
    'Unend': 1008,
    'Urban Product': 1009,
    'Usagi Ou': 1010,
    'V-sign': 1011,
    'VAP': 1012,
    'VCRWORKS': 1013,
    'VROOOOM': 1014,
    'Vasoon Animation': 1015,
    'Vega Entertainment': 1016,
    'Venet': 1017,
    'Viewworks': 1018,
    'Village Studio': 1019,
    'Visual 80': 1020,
    'Visual Flight': 1021,
    'Voil': 1022,
    'Volca': 1023,
    'W+K Tokyo': 1024,
    'W-Toon Studio': 1025,
    'WAO World': 1026,
    'WHOPPERS': 1027,
    'Wako Productions': 1028,
    'Wang Film Productions': 1029,
    'Watanabe Promotion': 1030,
    'Wawayu Animation': 1031,
    'Wei Chuang Jiang Xin': 1032,
    'Welz Animation Studios': 1033,
    'Whatever Co.': 1034,
    'White Fox': 1035,
    'Will Palette': 1036,
    'Windy Studio': 1037,
    'Wit Studio': 1038,
    'Wolf Smoke Studio': 1039,
    'Wolfsbane': 1040,
    'Wonder Cat Animation': 1041,
    'WonderLand': 1042,
    'Wong Ping Animation Lab': 1043,
    'Wulifang': 1044,
    'XEBEC M2': 1045,
    'XFLAG': 1046,
    'XFLAG Pictures': 1047,
    'Xanthus Media': 1048,
    'Xebec': 1049,
    'Xiaoming Taiji': 1050,
    'Xing Xing Donghua': 1051,
    'Xing Yi Kai Chen': 1052,
    'Xuni Ying Ye': 1053,
    'YHKT Entertainment': 1054,
    'YURUPPE Inc.': 1055,
    'Yamamura Animation': 1056,
    'Yamato Works': 1057,
    'Yamiken': 1058,
    'Yaoyorozu': 1059,
    'Yasuda Genshou Studio by Xenotoon': 1060,
    'Year Young Culture': 1061,
    'Yi Chen Animation': 1062,
    'Yinhe Changxing Culture': 1063,
    'Yokohama Animation Laboratory': 1064,
    'Yonago Gainax': 1065,
    'Yostar Pictures': 1066,
    'Youku': 1067,
    'Youliao Studio': 1068,
    'Yudubai Animation': 1069,
    'Yuhodo': 1070,
    'Yumeta Company': 1071,
    'Zelico Film': 1072,
    'Zero-G': 1073,
    'Zero-G Room': 1074,
    'Zexcs': 1075,
    'Zuiyo': 1076,
    'aNCHOR': 1077,
    'ame pippin': 1078,
    'animate Film': 1079,
    'asread.': 1080,
    'cogitoworks': 1081,
    'd00r works': 1082,
    'domerica': 1083,
    'drop': 1084,
    'dwarf': 1085,
    'evg': 1086,
    'feel.': 1087,
    'flag Co.': 1088,
    'foodunited.': 1089,
    'happyproject': 1090,
    'helo.inc': 1091,
    'iDRAGONS Creative Studio': 1092,
    'l-a-unch・BOX': 1093,
    'lxtl': 1094,
    'maroyaka': 1095,
    'miHoYoAnime': 1096,
    'monofilmo': 1097,
    'pH Studio': 1098,
    'production doA': 1099,
    'qmotri': 1100,
    'soket': 1101,
    'studio ALBLE': 1102,
    'studio MOTHER': 1103,
    'studio NAGURI': 1104,
    'studio YOG': 1105,
    'studio hb': 1106,
    'studio2 Animation Lab': 1107,
    'studio42': 1108,
    'sugarsaltpepper': 1109,
    'team Yamahitsuji': 1110,
    'teamKG': 1111,
    'teevee graphics': 1112,
    'trenova': 1113,
    'ufotable': 1114,
    'uzupiyo Animation & Digital Works': 1115,
    'yell': 1116,
}

# Tag mapping based on the genres from your list
# This dictionary maps genre/theme names fetched from the API to their corresponding numerical IDs in the database.
tag_map = {
    'Action': 1,
    'Adventure': 2,
    'Avant Garde': 3,
    'Award Winning': 4,
    'Boys Love': 5,
    'Comedy': 6,
    'Drama': 7,
    'Fantasy': 8,
    'Girls Love': 9,
    'Gourmet': 10,
    'Horror': 11,
    'Mystery': 12,
    'Romance': 13,
    'Sci-Fi': 14,
    'Slice of Life': 15,
    'Sports': 16,
    'Supernatural': 17,
    'Suspense': 18,
    'Ecchi': 19,
    'Erotica': 20,
    'Hentai': 21,
    'Adult Cast': 22,
    'Anthropomorphic': 23,
    'CGDCT': 24,
    'Childcare': 25,
    'Combat Sports': 26,
    'Crossdressing': 27,
    'Delinquents': 28,
    'Detective': 29,
    'Educational': 30,
    'Gag Humor': 31,
    'Gore': 32,
    'Harem': 33,
    'High Stakes Game': 34,
    'Historical': 35,
    'Idols (Female)': 36,
    'Idols (Male)': 37,
    'Isekai': 38,
    'Iyashikei': 39,
    'Love Polygon': 40,
    'Magical Sex Shift': 41,
    'Mahou Shoujo': 42,
    'Martial Arts': 43,
    'Mecha': 44,
    'Medical': 45,
    'Military': 46,
    'Music': 47,
    'Mythology': 48,
    'Organized Crime': 49,
    'Otaku Culture': 50,
    'Parody': 51,
    'Performing Arts': 52,
    'Pets': 53,
    'Psychological': 54,
    'Racing': 55,
    'Reincarnation': 56,
    'Reverse Harem': 57,
    'Love Status Quo': 58,
    'Samurai': 59,
    'School': 60,
    'Showbiz': 61,
    'Space': 62,
    'Strategy Game': 63,
    'Super Power': 64,
    'Survival': 65,
    'Team Sports': 66,
    'Time Travel': 67,
    'Vampire': 68,
    'Video Game': 69,
    'Visual Arts': 70,
    'Workplace': 71,
    'Urban Fantasy': 72,
    'Villainess': 73,
    'Josei': 74,
    'Kids': 75,
    'Seinen': 76,
    'Shoujo': 77,
    'Shounen': 78,
    'NO TAGS': 78,
}

TAG_ID_RANGE = range(1, 79) # Define the valid range for Tag IDs.

# Function to map Jikan API scores (0-10) to a rating scale (1-10), defaulting to 5 if no score.
def map_score_to_rating(score):
    return str(round(score)) if score else '5'

# Function to sanitize text for SQL insertion by escaping single quotes.
def sanitize(text):
    return text.replace("'", "''") if text else ''

# Function to fetch data from a given URL with retry logic for robustness against transient network issues.
def fetch_with_retry(url, retries=3, delay=3):
    for attempt in range(retries):
        try:
            res = requests.get(url)
            if res.status_code == 200:
                return res
            print(f"Attempt {attempt+1}: Failed to fetch {url} (Status Code: {res.status_code})")
        except Exception as e:
            print(f"Attempt {attempt+1}: Error fetching {url} - {e}")
        time.sleep(delay)
    return None

skipped_log = [] # Stores logs of anime entries that were skipped during processing.
anime_insert_values = [] # Accumulates SQL INSERT value strings for the Anime table.
anime_tags_insert_values = [] # Accumulates SQL INSERT value strings for the Anime_Tags table.
seen_titles = set() # Keeps track of anime titles already processed to avoid duplicates.
anime_id_counter = 1 # Simulated AnimeID for INSERT references (auto-increment in actual DB).

# Every 50 pages is around 1000 anime entries
# Step 1: Fetch the first page from Jikan API to determine the total number of pages available.
first_page_url = 'https://api.jikan.moe/v4/top/anime?page=1'
first_res = fetch_with_retry(first_page_url)

if not first_res:
    raise Exception("❌ Could not fetch the first page to determine total number of pages.")

first_data = first_res.json()
last_visible_page = first_data.get('pagination', {}).get('last_visible_page', 0)

if last_visible_page == 0:
    raise Exception("❌ 'last_visible_page' not found in pagination data.")

# Step 2: Iterate over all pages dynamically from 1 up to the last visible page.
for page in tqdm(range(1, last_visible_page + 1), desc="Fetching and Processing Anime Pages", colour="blue"):
    url = f'https://api.jikan.moe/v4/top/anime?page={page}'
    res = fetch_with_retry(url)
    
    if res is None:
        print(f"❌ Permanently failed to fetch page {page}")
        continue

    anime_list = res.json().get('data', [])

    for anime in tqdm(anime_list, desc=f"Processing Page {page}", leave=False, colour="green"):
        # Extract and sanitize the anime title.
        title = sanitize(anime.get('title'))

        # Skip if the title is a duplicate.
        if title in seen_titles:
            skipped_log.append(f"{title} - Duplicate title")
            continue
        seen_titles.add(title)

        # Extract and validate anime type.
        type_ = anime.get('type')
        if type_ == 'Music':
            skipped_log.append(f"{title} - Type: Music")
            continue

        if type_ in ['TV Special', 'PV', 'CM']:
            type_ = 'Special'

        if type_ not in ['TV', 'Movie', 'ONA', 'OVA', 'Special']:
            skipped_log.append(f"{title} - Invalid type: {type_}")
            continue

        # Extract episodes and map status.
        episodes = anime.get('episodes') or 'NULL'
        status_map = {'Currently Airing': 'Airing', 'Finished Airing': 'Completed', 'Not yet aired': 'Upcoming'}
        status = status_map.get(anime.get('status'), 'Upcoming')

        # Extract and format airing dates.
        start = anime.get('aired', {}).get('from')
        end = anime.get('aired', {}).get('to')
        airing_start = f"'{start[:10]}'" if start else 'NULL'
        airing_end = f"'{end[:10]}'" if end else 'NULL'

        # Extract score, map to rating, sanitize synopsis and image URL.
        score = anime.get('score') or 5
        rating = map_score_to_rating(score)
        synopsis = sanitize(anime.get('synopsis') or '')
        image_url = sanitize(anime.get('images', {}).get('jpg', {}).get('image_url', ''))

        # Extract studio information.
        studios = anime.get('studios')
        if not studios:
            skipped_log.append(f"{title} - No studio")
            continue
        studio_name = studios[0]['name']
        StudioID = studio_map.get(studio_name)
        if not StudioID:
            skipped_log.append(f"{title} - Unknown studio: {studio_name}")
            continue

        # Extract and process genres and themes.
        genres = anime.get('genres', [])
        themes = anime.get('themes', [])
        genre_names = [g['name'] for g in genres]
        theme_names = [t['name'] for t in themes]
        all_tags = genre_names + theme_names

        # Skip hentai/NSFW content.
        if 'Hentai' in all_tags or 'NSFW' in all_tags or 'Erotica' in all_tags:
            skipped_log.append(f"{title} - Skipped due to genre/theme: {'Hentai' if 'Hentai' in all_tags else 'NSFW'}")
            continue

        # Map tags to IDs, defaulting to 'NO TAGS' if none are found.
        tag_ids = [tag_map[tag_name] for tag_name in all_tags if tag_name in tag_map]
        if not tag_ids:
            tag_ids = [tag_map['NO TAGS']]

        # Append formatted SQL values for Anime table.
        anime_insert_values.append(
            f"('{title}', '{type_}', {episodes}, '{status}', {airing_start}, {airing_end}, '{rating}', '{synopsis}', {StudioID}, '{image_url}')"
        )

        # Append formatted SQL values for Anime_Tags table.
        for tag_id in tag_ids:
            anime_tags_insert_values.append(f"(@anime_id_{anime_id_counter}, {tag_id})")

        anime_id_counter += 1

# Write skipped anime log to a text file for review.
with open("skipped_log.txt", "w", encoding="utf-8") as log_file:
    log_file.write("Skipped Anime Log:\n")
    log_file.write("\n".join(skipped_log))

# Write generated SQL INSERT statements for Anime and Anime_Tags tables to an .sql file.
with open("anime_insert.sql", "w", encoding="utf-8") as f:
    f.write("START TRANSACTION;\n")
    anime_id = 1
    for val in anime_insert_values:
        f.write(f"INSERT INTO Anime (title, type, episodes, status, airing_start, airing_end, rating, synopsis, StudioID, image_url) VALUES {val};\n")
        f.write(f"SET @anime_id_{anime_id} = LAST_INSERT_ID();\n")
        anime_id += 1

    if anime_tags_insert_values:
        f.write("\nINSERT INTO Anime_Tags (AnimeID, TagID) VALUES\n")
        f.write(",\n".join(anime_tags_insert_values) + ";\n")

    f.write("COMMIT;\n")

# Print confirmation messages indicating the successful generation of SQL scripts and the number of entries.
print(f"✅ Anime insert script generated with {len(anime_insert_values)} entries.")
print(f"📦 Anime_Tags insert script generated with {len(anime_tags_insert_values)} entries.")